### PR TITLE
Develop migration test

### PR DESCRIPTION
**Pull request by miyconst**

### CODE REVIEW

**Comment by miyconst** [comment]
>Where is the source for test/StarDump.System.Tests/Resources/MigrationTestDump.sqlite3?

Which resource?

**Comment by miyconst** [comment]
I am currently trying to get the same thing in the `master` branch for `2.3.2` and then merge to `develop`.

**Comment by ubbeK** [comment]
I am just wondering how https://github.com/Starcounter/StarDump/blob/develop-migration-test/test/StarDump.System.Tests/Resources/MigrationTestDump.sqlite3 was created.

**Comment by miyconst** [comment]
>I am just wondering how https://github.com/Starcounter/StarDump/blob/develop-migration-test/test/StarDump.System.Tests/Resources/MigrationTestDump.sqlite3 was created.

I manually created the database with the migration steps, and then unloaded it. Manually checked that everything is correct in the dump.

**Comment by miyconst** [comment]
Closing this pull request in favor of the pull request to the master branch - [Database migration test](https://github.com/Starcounter/StarDump/pull/89).

**Pull request closed without merging**
